require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProjectRolesController do

  # This should return the minimal set of attributes required to create a valid
  # ProjectRole. As you add validations to ProjectRole, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProjectRolesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all project_roles as @project_roles" do
      project_role = ProjectRole.create! valid_attributes
      get :index, {}, valid_session
      assigns(:project_roles).should eq([project_role])
    end
  end

  describe "GET show" do
    it "assigns the requested project_role as @project_role" do
      project_role = ProjectRole.create! valid_attributes
      get :show, {:id => project_role.to_param}, valid_session
      assigns(:project_role).should eq(project_role)
    end
  end

  describe "GET new" do
    it "assigns a new project_role as @project_role" do
      get :new, {}, valid_session
      assigns(:project_role).should be_a_new(ProjectRole)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_role as @project_role" do
      project_role = ProjectRole.create! valid_attributes
      get :edit, {:id => project_role.to_param}, valid_session
      assigns(:project_role).should eq(project_role)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProjectRole" do
        expect {
          post :create, {:project_role => valid_attributes}, valid_session
        }.to change(ProjectRole, :count).by(1)
      end

      it "assigns a newly created project_role as @project_role" do
        post :create, {:project_role => valid_attributes}, valid_session
        assigns(:project_role).should be_a(ProjectRole)
        assigns(:project_role).should be_persisted
      end

      it "redirects to the created project_role" do
        post :create, {:project_role => valid_attributes}, valid_session
        response.should redirect_to(ProjectRole.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_role as @project_role" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectRole.any_instance.stub(:save).and_return(false)
        post :create, {:project_role => { "name" => "invalid value" }}, valid_session
        assigns(:project_role).should be_a_new(ProjectRole)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectRole.any_instance.stub(:save).and_return(false)
        post :create, {:project_role => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested project_role" do
        project_role = ProjectRole.create! valid_attributes
        # Assuming there are no other project_roles in the database, this
        # specifies that the ProjectRole created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProjectRole.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => project_role.to_param, :project_role => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested project_role as @project_role" do
        project_role = ProjectRole.create! valid_attributes
        put :update, {:id => project_role.to_param, :project_role => valid_attributes}, valid_session
        assigns(:project_role).should eq(project_role)
      end

      it "redirects to the project_role" do
        project_role = ProjectRole.create! valid_attributes
        put :update, {:id => project_role.to_param, :project_role => valid_attributes}, valid_session
        response.should redirect_to(project_role)
      end
    end

    describe "with invalid params" do
      it "assigns the project_role as @project_role" do
        project_role = ProjectRole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectRole.any_instance.stub(:save).and_return(false)
        put :update, {:id => project_role.to_param, :project_role => { "name" => "invalid value" }}, valid_session
        assigns(:project_role).should eq(project_role)
      end

      it "re-renders the 'edit' template" do
        project_role = ProjectRole.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProjectRole.any_instance.stub(:save).and_return(false)
        put :update, {:id => project_role.to_param, :project_role => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_role" do
      project_role = ProjectRole.create! valid_attributes
      expect {
        delete :destroy, {:id => project_role.to_param}, valid_session
      }.to change(ProjectRole, :count).by(-1)
    end

    it "redirects to the project_roles list" do
      project_role = ProjectRole.create! valid_attributes
      delete :destroy, {:id => project_role.to_param}, valid_session
      response.should redirect_to(project_roles_url)
    end
  end

end
